#!/bin/bash

SED=$(which sed);

#
# default user for reset password hook is "admin", but you can override it inside function _setPassword
#
#


function _setPassword() {

        local user='admin';

        while [ "$1" != "" ]; 
        do
          case $1 in
            -u )       shift
              local user=$1
              ;;
            -p )       shift
              local password=$1
              ;;
          esac
          shift
        done

    NEO4J_SERVER_PROP_FILE="${CARTRIDGE_APP_HOME}/conf/neo4j-server.properties"
    $SED -i "s/^org.neo4j.server.credentials=.*/org.neo4j.server.credentials=${user}:${password}/" $NEO4J_SERVER_PROP_FILE;

}
